id = "one-black-theme"
name = "One Black Theme"
schema_version = 1
version = "0.0.4"
authors = ["Serhii Boreiko <jestersunborn@gmail.com>"]
description = "One Dark got even dar..kier"
repository = "https://github.com/serhiiboreiko/one-black-theme-zed"
